- name: Install Database Packages
  when: ansible_facts['hostname'] == "database"
  apt:
    name: "{{ database_packages }}"    # this values is coming from main_vars.yaml.
    state: latest                     # Because we already defined them.   
    