  - name: Test Play 1
    hosts: all    # you can modify here and work on your specific server 
    gather_facts: "{{facts}}" 
    vars_files:
      - ../variables/main_vars.yaml
    tasks: 
      - include: ../tasks/ping.yaml  # if you create new task you  have to give the releative path in the playbooks.yaml file 
      - include: ../tasks/bootstrap.yaml
      - include: ../tasks/web_server_packages.yaml
      - include: ../tasks/database_packages.yaml
      - include: ../tasks/start_apache.yaml 